services:
  - type: web
    name: anloga-cashbook
    runtime: static
    buildCommand: npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: "/(.*)"
        destination: /index.html